baseURL = 'https://kamilaprz.github.io'
languageCode = 'en-uk'
title = 'Quick notes'
theme = "ananke"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Kamila Przychodzen"
favicon = ""
site_logo = ""
description = "Quick notess, snippets, thoughts."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-near-black"
recent_posts_number = 10
